### ISSUE TITLE
rsqlite TRUE/FALSE error

### ISSUE THREAD

**Issue by JARS3N** [ankane/dbx#10]
trying to connect to a MySQL db and getting this error
```
db <-dbxConnect(
    adapter = 'mysql',
    dbname = "table",
    url = "url",
    variables=list(
    user = "user",
    port = 3306,
    password = "pwd")
  )
```

"Error in if (adapter == "rsqlite") { : 
  missing value where TRUE/FALSE needed"

**Comment by ankane** [comment]
Hi @JARS3N, thanks for reporting 👍 I believe the issue is the URL you're passing is invalid. I pushed a change to master to give a better error message. You'll typically want to use either `adapter` or `url`, not both. Also, `user`, `port`, and `password` shouldn't be nested in `variables`.
