### ISSUE TITLE
Error in dbxUpsert/dbxUpdate  when where_cols includes multiple columns

### ISSUE THREAD

**Issue by socialsoft** [ankane/dbx#12]
When the order of columns in where_cols is different than in the data frame, the dbxUpsert/dbxUpdate would raise ""where_cols not in records" error. I don't think the order is important and it is difficult to control it. The fix for my local repo is to use the setequal() function instead of identical() in the following.

  if (!identical(intersect(cols, where_cols), where_cols)) {
    stop("where_cols not in records")
  }

**Comment by ankane** [comment]
Thanks @socialsoft, didn't mean to make the ordering important. Fixed with your suggestion on master 👍
