### ISSUE TITLE
500 records returned by default?

### ISSUE THREAD

**Issue by cspenn** [ankane/dbx#2]
When using: 

```
getquery <-
    c(
      "SELECT * from MYTABLE order by `Date` ASC"
    )
```

with dbx, it returns a dataframe of 500 rows.

When using RMySQL, it returns the full 32,625 rows that are in the DB.

Is this intended behavior?

**Comment by ankane** [comment]
Hey @cspenn, thanks for reporting 👍 Fixed now.
