### ISSUE TITLE
dbxUpsert - Error: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint

### ISSUE THREAD

**Issue by janush1985** [ankane/dbx#25]
Hello,

Well done on this phenomenal package. Cheers!

I am unable to get following code to work:

`db <- dbxConnect(adapter="sqlite", dbname="my database")
table <- "forecasts"
DBI::dbCreateTable(db, table, data.frame(id=1:3, temperature=20:22))

records <- data.frame(id=c(3, 4), temperature=c(20, 25))
dbxUpsert(db, table, records, where_cols=c("id"))
`

I get following error msg:

"Error: ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint"

Other functions such as dbxUpdate, dbxInsert are working ok.

Help much appreciated!

Best,
Janush

**Comment by ankane** [comment]
Hey @janush1985, that error is coming from SQLite. You'll need to make sure the columns in `where_cols` (`id` in this case) have either a primary key or unique constraint.

**Comment by janush1985** [comment]
Hi man, 

Thanks a lot for the tip. Much appreciated.

All the best!
