### ISSUE TITLE
Error updating datetime field in SQL server

### ISSUE THREAD

**Issue by rochifebo** [ankane/dbx#27]
Hi,

I'am using dbxUpdate to update a SQL Server 2019 table and I get this error

```
Error: nanodbc/nanodbc.cpp:1655: 22007: [Microsoft][ODBC SQL Server Driver][SQL Server]Conversion failed when converting date and/or time from character string. 
<SQL> 'UPDATE "Completed_Actions" SET "END_DATE" = '2021-04-01 00:00:00.000000' WHERE "ID" IN (37505674, 37505675)'
```
the error is related to the fact that SQL Server datetime columns are only able to store fractional seconds to millisecond precision (3 decimal places).  

Thank you for the useful library and your support

**Comment by ankane** [comment]
Hey @rochifebo, thanks for reporting! It's not ideal, but you should be able to covert the column to a string before passing to `dbxUpdate`:

```r
records$column <- format(records$column, tz="Etc/UTC", "%Y-%m-%d %H:%M:%OS3")
```

dbx could lookup the column type to differentiate between `datetime` and `datetime2`, or have an option for the precision to use for `POSIXct` values, but I don't think it's worth the extra complexity right now.
