### ISSUE TITLE
encoding problems with windows

### ISSUE THREAD

**Issue by bpresentati** [ankane/dbx#29]
I'm building a workflow that takes an excel file that has special characters and is saved in utf-8 and uploads it to a mysql database where the fields are defined as utf8_general_ci. In R the encoding of the strings in the dataframes before I try to insert them into the DB is utf-8. However, when they make it onto the DB, they are somehow interpreted as the windows native standard and it seems as if there's nothing I can do about this if I'm using the dbx package. Would anyone have suggestions what I could try?

**Comment by ankane** [comment]
Hey @bpresentati, I haven't done much with encodings, but if you can create a minimal script to reproduce, I can try to look into it. Does it work as expected if you use DBI directly?
