### ISSUE TITLE
Error when using dbxUpsert to add a record that solely consists of primary key columns.

### ISSUE THREAD

**Issue by sempeelmanae** [ankane/dbx#4]
Using the MySQL adapter and dbxUpsert to add a record that consists solely of primary key columns (i.e. when the column names of the 'table'-argument are exactly the columns passed to 'where_cols'-argument) I get the following error:

` 
Error in .local(conn, statement, ...) : 
  could not run statement: Unknown column '' in 'field list' 
`

Currently I solved this issue by adding a dummy column.

**Comment by ankane** [comment]
Hey @sempeelmanae, thanks for reporting 👍 Should be fixed on master.

```r
devtools::install_github("ankane/dbx")
```
