### ISSUE TITLE
 dbxUpsert RSQLite "Error in result_create(conn@ptr, statement)"

### ISSUE THREAD

**Issue by meandreatta** [ankane/dbx#9]
I noticed while trying to run dbxUpsert using the demo code described in the read me of the dbx package I keep encountering this error:
"Error in result_create(conn@ptr, statement) : near "ON": syntax error"

Here's the code below that caused the error:
db <- dbxConnect(adapter="sqlite", dbname=":memory:")

table <- "forecasts"
DBI::dbCreateTable(db, table, data.frame(id=c(1,2), temperature=c(20,22)))
dbxInsert(db, "forecasts", data.frame(id=c(1,2), temperature=c(20,22)))
dbReadTable(db,"forecasts")

#update entries
records <- data.frame(id=c(1, 2), temperature=c(16, 13))
dbxUpdate(db, table, records, where_cols=c("id")) 
dbReadTable(db,"forecasts")

#upsert entries
records <- data.frame(id=c(2, 3), temperature=c(20, 25))
dbxUpsert(db, "forecasts", records, where_cols=c("id"))
dbReadTable(db,"forecasts")

I'm running the most recent versions of RSQLite (2.1.1) dbx (0.23) and DBI(1.0.0.9001) using R version 3.5

**Comment by ankane** [comment]
Hey @meandreatta, you'll need to use RSQLite from GitHub, as there hasn't been a release for SQLite 3.24+ yet.

```r
devtools::install_github("r-dbi/RSQLite")
```

**Comment by meandreatta** [comment]
I've updated to the development RSQLite version but run into a separate issue when I run the dbxUpsert command

```
records <- data.frame(id=c(2, 3), temperature=c(20, 25))
dbxUpsert(db, "forecasts", records, where_cols=c("id"))
```

"Error in result_create(conn@ptr, statement) : 
  ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint"

My understanding is that the "id" column is the primary key unless the underlying sql command is looking for something else?

**Comment by ankane** [comment]
You'll need to set a primary key or unique index. When creating the table, you can do:

```r
fields <- list(id="INTEGER PRIMARY KEY", temperature="INTEGER")
DBI::dbCreateTable(db, "forecasts", data.frame(), fields=fields)
```

**Comment by meandreatta** [comment]
Thanks that's exactly what I needed! I was worried for a moment that I would have to go the long way around for updating and inserting new records :)
